# wallet-watcher-api/docker-compose.yml
services:
  express_api:
    build: .
    container_name: wallet-watcher-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "4000:4000"        # public for now; you can proxy later