name: Deploy API

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}   # deploy
          key:      ${{ secrets.SSH_KEY }}    # same private key as before
          script: |
            set -e
            # put the code in its own folder
            if [ ! -d ~/wallet-watcher-api ]; then
              git clone --depth 1 https://github.com/s-Milo-s/wallet-watchers-api.git ~/wallet-watcher-api
            fi
            cd ~/wallet-watcher-api
            git pull origin master

            # build & (re)create only this stack
            docker compose build
            docker compose up -d --force-recreate
            docker image prune -f